-- Atomic compare-and-rotate for refresh-token sessions (Sprint 01A).
--
-- KEYS[1] = auth:refresh:family:<familyId>
-- ARGV[1] = sha256(presentedSecret)  -- hashed by the caller; this script never sees plaintext
-- ARGV[2] = sha256(newSecret)        -- pre-generated by the caller; only committed if this call wins
-- ARGV[3] = now (epoch ms, passed by the caller for deterministic timestamps)
-- ARGV[4] = ttlSeconds                -- REFRESH_TOKEN_TTL_SECONDS, sliding expiration
--
-- Returns a 2-element array: { outcome, userId }
--   outcome = "missing" | "reused" | "ok"
--   userId  = the family's owner, or "" when outcome is "missing" (nothing to read)
--
-- Runs as a single uninterruptible unit — Redis serializes all EVAL calls
-- against the same key, so two concurrent refresh requests presenting the
-- same starting secret can never both observe a match: whichever the server
-- processes first rotates and wins ("ok"); the other sees the
-- already-updated hash, no longer matches, and is treated as reuse ("reused"),
-- which deletes the family in the same atomic step. Strict single-use, no
-- grace tolerance — see docs/CLAUDE.md's Sprint 01A design notes.

local raw = redis.call('GET', KEYS[1])
if not raw then
  return {'missing', ''}
end

local record = cjson.decode(raw)
if record.currentSecretHash ~= ARGV[1] then
  -- Not the current secret: either a stale/reused secret, or the losing side
  -- of a concurrent-refresh race. Either way, revoke the whole family.
  redis.call('DEL', KEYS[1])
  return {'reused', record.userId}
end

record.currentSecretHash = ARGV[2]
record.lastUsedAt = tonumber(ARGV[3])
redis.call('SET', KEYS[1], cjson.encode(record), 'EX', ARGV[4])
return {'ok', record.userId}
